// ================== AUTH ==================

# Register for admin
###
POST http://localhost:8080/api/auth/admin-register
Content-Type: application/json

{
    "username": "tranvudpqn1234",
    "name": "Trần Gia Kinh",
    "password": "Admin123@",
    "email": "tranleanhvu10011999@gmail.com"
}


# Register for trainee
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "huydpqn1234",
    "name": "Phạm Đức Huy",
    "password": "Admin123@",
    "email": "huyph2599@gmail.com",
    "phone": "0377670509",
    "address": "01 Võ Văn Ngân, phường Bình Thọ, quận Thủ Đức, TP HCM",
    "typeUser": "trainee"
}

# Login
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "toandpqn123",
    "password": "Admin123@",
    "typeUser": "trainer"
}