// ================== AUTH ==================

# Get list account
###
GET http://localhost:8080/api/auth/


# Get list account of admin
###
GET http://localhost:8080/api/auth/getAdmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8


# Get list account of trainer
###
GET http://localhost:8080/api/auth/getTrainer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

# Register for admin
###
POST http://localhost:8080/api/auth/admin-register
Content-Type: application/json

{
    "username": "tranvudpqn123",
    "name": "Trần Gia Kinh",
    "password": "Admin123@",
    "email": "tranleanhvu10011999@gmail.com"
}


# Register for trainee
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "toan",
    "name": "Trần Đình Toàn",
    "password": "Admin123@",
    "email": "toantd2599@gmail.com",
    "phone": "0377670509",
    "address": "01 Võ Văn Ngân, phường Bình Thọ, quận Thủ Đức, TP HCM",
    "typeUser": "trainer"
}

# Login
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "quocdpqn123",
    "password": "Admin123@",
    "typeUser": "trainee"
}



// ================== CLASS ==================

# Add new class
###
POST http://localhost:8080/api/class
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "Id": null,
    "ClassName": "new class2",
    "Capacity": 20,
    "StartTime": "31/05/2021",
    "EndTime": "31/05/2021",
    "isDeleted": false
}


# Get list class
###
GET http://localhost:8080/api/class
Content-Type: application/json
# Trainee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



# Edit class
###
PUT http://localhost:8080/api/class/60a75ccbec1f7025c8d2fef9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "ClassName": "Class 00",
    "Capacity": 50,
    "StartTime": "22/06/2021",
    "EndTime": "22/06/2020"
}


# Remove class
###
DELETE http://localhost:8080/api/class/60a75ccbec1f7025c8d2fef9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8


# Get class
###
GET http://localhost:8080/api/class/60a75ccbec1f7025c8d2fef9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRkYjk1N2FhNjBjN2M3YzNlYTMiLCJ0eXBlVXNlciI6InRyYWluZXIiLCJpYXQiOjE2MjE4NjAxMDJ9.9jeoS9FkyEk6QyeOBEVLuK_sEf7QhhkihQUIk4Y20dU



// ================== TOPIC ==================

# Add new topic
###
POST http://localhost:8080/api/topic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "TopicName": "Other"
}


# Get list topic
###
GET http://localhost:8080/api/topic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



// ================== QUESTION ==================

# Add new question
###
POST http://localhost:8080/api/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "QuestionContent": "What aspects of the topic/source course could be improve? (Những điểm có thể cải tiến ở môn học/khóa học này?)",
    "TopicId": "60a8edbea86b7c42384e8bee"
}

# Get list question
###
GET http://localhost:8080/api/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8


# Get question detail
###
GET http://localhost:8080/api/question/?Id=60a8eef3a86b7c42384e8bef
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8


# Get list question of topic
###
POST http://localhost:8080/api/question/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "TopicId": "60a8ed6ba86b7c42384e8beb"
}


# Edit question
###
PUT http://localhost:8080/api/question/60a7c850f475020888a1b9c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "QuestionContent": "Question 01",
    "TopicId": "60a7bba427655242a834f5c7"
}


# Delete question
###
DELETE http://localhost:8080/api/question/60a7c850f475020888a1b9c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



// ================== TYPE FEEDBACK ==================

# Add new type feedback
###
POST http://localhost:8080/api/type-feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "TypeName": "Offline"
}


# Get list type feedback
###
GET http://localhost:8080/api/type-feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



// ================== FEEDBACK ==================

# Add new feedback
###
POST http://localhost:8080/api/feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "Title": "New Feedback",
    "TypeFeedbackId": "60a8e4e8141a2a45a4b1ed0b",
    "listQuestion": [
        "60a8eef3a86b7c42384e8bef", 
        "60a8ef3aa86b7c42384e8bf0",
        "60a8ef7fa86b7c42384e8bf1",
        "60a8eff8a86b7c42384e8bf2",
        "60a8f031a86b7c42384e8bf3",
        "60a8f0bea86b7c42384e8bf6",
        "60a8f119a86b7c42384e8bf7",
        "60a8f1d3a86b7c42384e8bf8",
        "60a8f233a86b7c42384e8bf9",
        "60aa245c0f97d600157614b8"
    ]
}


# Get list feedback
###
GET http://localhost:8080/api/feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRjMTk1N2FhNjBjN2M3YzNlYTIiLCJ0eXBlVXNlciI6InRyYWluZWUiLCJpYXQiOjE2MjE4NjAwNjB9.2fpi3Fs7bYl233OHKppcDVZwmcVz3aG1TubOh_ZWj9E



# Delete feedback
###
DELETE http://localhost:8080/api/feedback/60a9e10bb2be0c27844d14ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



# Update feedback
###
PUT http://localhost:8080/api/feedback/60a9e10bb2be0c27844d14ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "Title": "New Feedback2",
    "TypeFeedbackId": "60a8e4e8141a2a45a4b1ed0b",
    "listQuestion": [
        "60a8eef3a86b7c42384e8bef", 
        "60a8ef3aa86b7c42384e8bf0",
        "60a8f031a86b7c42384e8bf3",
        "60a8f119a86b7c42384e8bf7"
    ]
}



# Get feedback
###
GET http://localhost:8080/api/feedback/60aa2adfc2188327980f86d3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



// ================== MODULE ==================

# Add new module
###
POST http://localhost:8080/api/module
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "ModuleName": "Module",
    "StartTime": "31/5/2021",
    "EndTime": "31/5/2021",
    "AdminId": "current admin",
    "FeedbackId": "60aa2adfc2188327980f86d3",
    "FeedbackStartTime": "31/5/2021",
    "FeedbackEndTime": "31/5/2021"
}


# Update module
###
PUT http://localhost:8080/api/module/60aa6a1501e23f0b98f0679d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "ModuleName": "String MVC",
    "StartTime": "24/05/2021",
    "EndTime": "24/05/2021",
    "AdminId": "60a724ba957aa60c7c7c3ea1",
    "FeedbackId": "60aa2adfc2188327980f86d3",
    "FeedbackStartTime": "24/05/2021",
    "FeedbackEndTime": "24/05/2021"
}

# Remove module
###
DELETE http://localhost:8080/api/module/60aa6a1501e23f0b98f0679d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8


# Get module
###
GET http://localhost:8080/api/module/60aa6a1501e23f0b98f0679d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

# Get list module
###
GET http://localhost:8080/api/module
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRjMTk1N2FhNjBjN2M3YzNlYTIiLCJ0eXBlVXNlciI6InRyYWluZWUiLCJpYXQiOjE2MjE4NjAwNjB9.2fpi3Fs7bYl233OHKppcDVZwmcVz3aG1TubOh_ZWj9E



// ================== ASSGNMENT ==================

# Add new assignment
###
POST http://localhost:8080/api/assignment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "ModuleId": "60acb0b396b4102e005c2e87",
    "ClassId": "60a75ccbec1f7025c8d2fef9",
    "TrainerId": "60acb41f7f3585254cb0093f"
}


# Update assignment
###
PUT http://localhost:8080/api/assignment/60ab5cf36d50a8379435dd43
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "ModuleId": "60aa6bb5fdd5941f88e6aa61",
    "ClassId": "60a75ccbec1f7025c8d2fef9",
    "TrainerId": "60a724db957aa60c7c7c3ea3"
}


# Get list assignment
###
GET http://localhost:8080/api/assignment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



# Delete assignment
###
DELETE http://localhost:8080/api/assignment/60b5ad73c8325d0015737dd7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8






// ================== ENROLLMENT ==================

# Add new enrollment
###
POST http://localhost:8080/api/enrollment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "ClassId": "60a75ccbec1f7025c8d2fef9",
    "TraineeId": "60a724c1957aa60c7c7c3ea2"
}

# Update enrollment
###
PUT http://localhost:8080/api/enrollment/60a724c1957aa60c7c7c3ea2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8

{
    "ClassId": "60a75ccbec1f7025c8d2fef9",
    "TraineeId": "60a724c1957aa60c7c7c3ea2"
}


# Get enrollment
###
GET http://localhost:8080/api/enrollment/60a724c1957aa60c7c7c3ea2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8


# Get list enrollment
###
GET http://localhost:8080/api/enrollment/filter/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



// ================== ANSWER ==================

# Add new anwser
###
POST http://localhost:8080/api/answer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRjMTk1N2FhNjBjN2M3YzNlYTIiLCJ0eXBlVXNlciI6InRyYWluZWUiLCJpYXQiOjE2MjE4NjAwNjB9.2fpi3Fs7bYl233OHKppcDVZwmcVz3aG1TubOh_ZWj9E

{
    "listAnswer": [
        {
            "ClassId": "60a75ccbec1f7025c8d2fef9",
            "ModuleId": "60aa6bb5fdd5941f88e6aa61",
            "QuestionId": "60a8eef3a86b7c42384e8bef",
            "Value": 100
        },
        {
            "ClassId": "60a75ccbec1f7025c8d2fef9",
            "ModuleId": "60aa6bb5fdd5941f88e6aa61",
            "QuestionId": "60a8ef3aa86b7c42384e8bf0",
            "Value": 100
        }
    ]
}


# Get list answer
###
GET http://localhost:8080/api/answer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJ0eXBlVXNlciI6ImFkbWluIiwiaWF0IjoxNjIxODU5NDMwfQ.-GljSrlUF4b3nl8ojzpk1xK1O-_MX5B6a31g8u5eTp8



// ================== COMMENT ==================
# Add new comment
###
POST http://localhost:8080/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRjMTk1N2FhNjBjN2M3YzNlYTIiLCJ0eXBlVXNlciI6InRyYWluZWUiLCJpYXQiOjE2MjE4NjAwNjB9.2fpi3Fs7bYl233OHKppcDVZwmcVz3aG1TubOh_ZWj9E

{
    "ClassId": "60a75ccbec1f7025c8d2fef9",
    "ModuleId": "60aa6a1501e23f0b98f0679d",
    "Comment": "ok het"
}

# Get list comment by trainee
###
GET http://localhost:8080/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRjMTk1N2FhNjBjN2M3YzNlYTIiLCJ0eXBlVXNlciI6InRyYWluZWUiLCJpYXQiOjE2MjE4NjAwNjB9.2fpi3Fs7bYl233OHKppcDVZwmcVz3aG1TubOh_ZWj9E


// ================== TRAINEE ASSIGNMENT ==================
# Add new assignment
###
POST http://localhost:8080/api/trainee-assignment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRjMTk1N2FhNjBjN2M3YzNlYTIiLCJ0eXBlVXNlciI6InRyYWluZWUiLCJpYXQiOjE2MjE4NjAwNjB9.2fpi3Fs7bYl233OHKppcDVZwmcVz3aG1TubOh_ZWj9E

{
    "RegistrationCode": "CL6M6T1621843187410"
}