// ================== AUTH ==================

# Get list account
###
GET http://localhost:8080/api/auth/

# Register for admin
###
POST http://localhost:8080/api/auth/admin-register
Content-Type: application/json

{
    "username": "tranvudpqn123",
    "name": "Trần Gia Kinh",
    "password": "Admin123@",
    "email": "tranleanhvu10011999@gmail.com"
}


# Register for trainee
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "toandpqn1234",
    "name": "Phạm Hoàng Toán",
    "password": "Admin123@",
    "email": "toanph2599@gmail.com",
    "phone": "0377670509",
    "address": "01 Võ Văn Ngân, phường Bình Thọ, quận Thủ Đức, TP HCM",
    "typeUser": "trainer"
}

# Login
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "toandpqn1234",
    "password": "Admin123@",
    "typeUser": "trainer"
}



// ================== CLASS ==================

# Add new class
###
POST http://localhost:8080/api/class
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJpYXQiOjE2MjE1NzcyNzB9.sT_-4QbagBAaVfArXoa7v8REDmeYBrZw1YA7fMxQTIs

{
    "ClassName": "Class 03",
    "Capacity": 50,
    "StartTime": "22/06/2021",
    "EndTime": "22/06/2020"
}


# Get list class
###
GET http://localhost:8080/api/class/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJpYXQiOjE2MjE1NzcyNzB9.sT_-4QbagBAaVfArXoa7v8REDmeYBrZw1YA7fMxQTIs


# Edit class
###
PUT http://localhost:8080/api/class/60a75ccbec1f7025c8d2fef9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJpYXQiOjE2MjE1NzcyNzB9.sT_-4QbagBAaVfArXoa7v8REDmeYBrZw1YA7fMxQTIs

{
    "ClassName": "Class 00",
    "Capacity": 50,
    "StartTime": "22/06/2021",
    "EndTime": "22/06/2020"
}


# Remove class
###
DELETE http://localhost:8080/api/class/60a75ccbec1f7025c8d2fef9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJpYXQiOjE2MjE1NzcyNzB9.sT_-4QbagBAaVfArXoa7v8REDmeYBrZw1YA7fMxQTIs



// ================== CLASS ==================

# Add new topic
###
POST http://localhost:8080/api/topic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MGE3MjRiYTk1N2FhNjBjN2M3YzNlYTEiLCJpYXQiOjE2MjE1NzcyNzB9.sT_-4QbagBAaVfArXoa7v8REDmeYBrZw1YA7fMxQTIs

{
    "TopicName": "Topic 01"
}